# -*- coding: utf-8 -*-
"""tebakkata .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QqirQw1k_7vaUUHnGhLQrUmsc6J3dxjb
"""

import random
 
print()
urname = input("What's ur name?")
print("Good Luck brodi!")
print('''
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~~~~~~ HALLOW CAKEUP! WELCOME TO GAME TEBAK KATA🥰 ~~~~~~
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ''')
print()
 
wordoption = ['pudding',
              'cake',
              'pastry',
              'pie',
              'icecream',
              'coupe',
              'pancake',
              'crepes',
              'milkshake']
                           
word = random.choice(wordoption)
 
print('''
---------------------------------------------
| 🍦🧁GUESS THE CHARACTERS OF DESSERT🧁🍦 |
---------------------------------------------
''')
 
guessed = '' 
# banyaknya percobaan
turns = 12
while turns > 0:
 
    # perhitungan berapa kali kegagalan
    failed = 0
 
    for char in word: # perbandingan karakter tsb dgn karakter dalam tebakan
        if char in guessed:
            print(char, end=" ")
        else:
            print("🐷")
 
            # tiap 1 kali gagal maka akan bertambah
            failed += 1
 
    if failed == 0: # jika kegagalannya 0 pemain akan menang
        print('''
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                ~~~~~~~~~~ CIEEE MENANGGG🎉, CONGRATS YAA! ~~~~~~~~~~
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                ''')
 
        # kata yang benar
        print("The word is: ", word)
        break
 
    # jika pemain memasukkan huruf yg salah akan diminta memasukkan huruf lain
    print()
    guess = input("YUKSKIEE TEBAK BROWW:")
    guessed += guess
 
    # memeriksa input huruf pada kata
    if guess not in word:
        turns -= 1
     # jika huruf tidak cocok dengan kata, maka salah
        print("Yahh salahh, ayoo coba tebak lagii")
 
        # mencetak jumlah percobaan pemain
        print("it's okey, masi ada", + turns, 'percobaan lagi')
 
        if turns == 0:
            print('''
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            ~~~~~~~~~~ YAHHH U LOSE😥, TTP SMGT Y BROW! ~~~~~~~~~~
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            ''')

